manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      # remote: zmkfirmware
      # Using urob's fork until https://github.com/zmkfirmware/zmk/pull/1451 get's merged
      remote: urob
      revision: main
      import: app/west.yml
  self:
    path: config
