manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: zoriya
      url-base: https://github.com/zoriya
  projects:
    - name: zmk
      # remote: zmkfirmware
      # Using urob's fork until https://github.com/zmkfirmware/zmk/pull/1451 get's merged
      # my fork is updated and cherry-picked the relevent commit from previous PR.
      remote: zoriya
      revision: main
      import: app/west.yml
  self:
    path: config
